import os

def test_pages_content():
    # Validate Pages setup presence locally if generated by workflow scripts
    assert os.path.exists("public/index.html")
    assert os.path.exists("public/.nojekyll")
    for file in ["40eridani_energy.png", "40eridani_feasibility.png"]:
        assert os.path.exists(f"public/{file}")
