name: Pages Link Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  linkcheck:
    runs-on: ubuntu-24.04
    steps:
  # No checkout needed; we only curl the public Pages URL
      - name: Wait for Pages propagation
        run: |
          echo "Sleeping 20s to allow cache propagation" && sleep 20
      - name: Quick HEAD check on Pages site
        run: |
          set -e
          URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}"
          echo "HEAD ${URL}"
          curl -sS -I "$URL" | head -n 5 || true
      - name: Verify key plot URLs
        run: |
          base="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}"
          fail=0
          for path in 40eridani_energy.png 40eridani_feasibility.png 40eridani_uq_tiny.png perf_summary.png perf_smoke.png; do
            url="$base/$path"
            code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            echo "$code $url"
            if [ "$code" != "200" ]; then fail=1; fi
          done
          exit $fail
