name: Update Repo Description

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/update-repo-description.yml'

permissions:
  contents: read

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Update repository description via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESC: "Optimizing positive-energy warp bubbles for 52c FTL missions (e.g., 40 Eridani A in 30 days) with UQ, V&V, and hardware mocks. Join the 2063 timeline!"
        run: |
          echo "Updating repository description at 2025-08-14 15:14 PDT"
          curl -sS -X PATCH \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/arcticoder/warp-bubble-optimizer \
            -d "{\"description\":\"${DESC}\"}"
